//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BizPackService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:SMSService", ConfigurationName="BizPackService.SMSServicePort")]
    internal interface SMSServicePort
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#send", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendResponse send(BizPackService.sendRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#send", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendResponse> sendAsync(BizPackService.sendRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message SendSmsRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#SendSms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.SendSmsResponse SendSms(BizPackService.SendSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#SendSms", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.SendSmsResponse> SendSmsAsync(BizPackService.SendSmsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendSmsAuthKeyRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSmsAuthKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendSmsAuthKeyResponse sendSmsAuthKey(BizPackService.sendSmsAuthKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSmsAuthKey", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendSmsAuthKeyResponse> sendSmsAuthKeyAsync(BizPackService.sendSmsAuthKeyRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendWapPushRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendWapPush", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendWapPushResponse sendWapPush(BizPackService.sendWapPushRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendWapPush", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendWapPushResponse> sendWapPushAsync(BizPackService.sendWapPushRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendVCalendarRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendVCalendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendVCalendarResponse sendVCalendar(BizPackService.sendVCalendarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendVCalendar", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendVCalendarResponse> sendVCalendarAsync(BizPackService.sendVCalendarRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendVCardRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendVCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendVCardResponse sendVCard(BizPackService.sendVCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendVCard", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendVCardResponse> sendVCardAsync(BizPackService.sendVCardRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.bizpack.ro/service.php) of message sendSmsFlashRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSmsFlash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendSmsFlashResponse sendSmsFlash(BizPackService.sendSmsFlashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSmsFlash", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendSmsFlashResponse> sendSmsFlashAsync(BizPackService.sendSmsFlashRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message checkStatusRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#checkStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.checkStatusResponse checkStatus(BizPackService.checkStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#checkStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.checkStatusResponse> checkStatusAsync(BizPackService.checkStatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message openSessionRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#openSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.openSessionResponse openSession(BizPackService.openSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#openSession", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.openSessionResponse> openSessionAsync(BizPackService.openSessionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message closeSessionRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#closeSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.closeSessionResponse closeSession(BizPackService.closeSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#closeSession", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.closeSessionResponse> closeSessionAsync(BizPackService.closeSessionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendSessionRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSession", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendSessionResponse sendSession(BizPackService.sendSessionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSession", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendSessionResponse> sendSessionAsync(BizPackService.sendSessionRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendSessionWapPushRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSessionWapPush", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendSessionWapPushResponse sendSessionWapPush(BizPackService.sendSessionWapPushRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSessionWapPush", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendSessionWapPushResponse> sendSessionWapPushAsync(BizPackService.sendSessionWapPushRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendSessionVCalendarRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSessionVCalendar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendSessionVCalendarResponse sendSessionVCalendar(BizPackService.sendSessionVCalendarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSessionVCalendar", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendSessionVCalendarResponse> sendSessionVCalendarAsync(BizPackService.sendSessionVCalendarRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message sendSessionVCardRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSessionVCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendSessionVCardResponse sendSessionVCard(BizPackService.sendSessionVCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSessionVCard", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendSessionVCardResponse> sendSessionVCardAsync(BizPackService.sendSessionVCardRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/service.php) of message sendSessionSmsFlashRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSessionSmsFlash", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.sendSessionSmsFlashResponse sendSessionSmsFlash(BizPackService.sendSessionSmsFlashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#sendSessionSmsFlash", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.sendSessionSmsFlashResponse> sendSessionSmsFlashAsync(BizPackService.sendSessionSmsFlashRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.bizpack.ro/wsi/service.php) of message showIpRequest does not match the default value (urn:SMSService)
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#showIp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        BizPackService.showIpResponse showIp(BizPackService.showIpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.xmlsoap.org/soap/envelope/#SMSService#showIp", ReplyAction="*")]
        System.Threading.Tasks.Task<BizPackService.showIpResponse> showIpAsync(BizPackService.showIpRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="send", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public System.DateTime date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int validity;
        
        public sendRequest()
        {
        }
        
        public sendRequest(string phone, string message, System.DateTime date, string sender, int validity)
        {
            this.phone = phone;
            this.message = message;
            this.date = date;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public sendResponse()
        {
        }
        
        public sendResponse(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSms", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class SendSmsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string source;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string destination;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public bool isUnicode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public System.DateTime scheduleDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string callbackUrl;
        
        public SendSmsRequest()
        {
        }
        
        public SendSmsRequest(string username, string password, string source, string destination, string body, bool isUnicode, System.DateTime scheduleDate, string callbackUrl)
        {
            this.username = username;
            this.password = password;
            this.source = source;
            this.destination = destination;
            this.body = body;
            this.isUnicode = isUnicode;
            this.scheduleDate = scheduleDate;
            this.callbackUrl = callbackUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSmsResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class SendSmsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public SendSmsResponse()
        {
        }
        
        public SendSmsResponse(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSmsAuthKey", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSmsAuthKeyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string authKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public System.DateTime scheduleDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int validity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string callbackUrl;
        
        public sendSmsAuthKeyRequest()
        {
        }
        
        public sendSmsAuthKeyRequest(string username, string authKey, string sender, string recipient, string message, System.DateTime scheduleDate, int validity, string callbackUrl)
        {
            this.username = username;
            this.authKey = authKey;
            this.sender = sender;
            this.recipient = recipient;
            this.message = message;
            this.scheduleDate = scheduleDate;
            this.validity = validity;
            this.callbackUrl = callbackUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSmsAuthKeyResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSmsAuthKeyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public sendSmsAuthKeyResponse()
        {
        }
        
        public sendSmsAuthKeyResponse(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendWapPush", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendWapPushRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public System.DateTime date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int validity;
        
        public sendWapPushRequest()
        {
        }
        
        public sendWapPushRequest(string phone, string url, string message, System.DateTime date, string sender, int validity)
        {
            this.phone = phone;
            this.url = url;
            this.message = message;
            this.date = date;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendWapPushResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendWapPushResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public sendWapPushResponse()
        {
        }
        
        public sendWapPushResponse(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVCalendar", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendVCalendarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string location;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public System.DateTime startDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public System.DateTime endDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public System.DateTime alarmDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public System.DateTime sendDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int validity;
        
        public sendVCalendarRequest()
        {
        }
        
        public sendVCalendarRequest(string recipient, string subject, string location, string description, System.DateTime startDatetime, System.DateTime endDatetime, System.DateTime alarmDatetime, System.DateTime sendDatetime, string sender, int validity)
        {
            this.recipient = recipient;
            this.subject = subject;
            this.location = location;
            this.description = description;
            this.startDatetime = startDatetime;
            this.endDatetime = endDatetime;
            this.alarmDatetime = alarmDatetime;
            this.sendDatetime = sendDatetime;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVCalendarResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendVCalendarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public sendVCalendarResponse()
        {
        }
        
        public sendVCalendarResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVCard", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendVCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string firstname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string lastname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string mobilephone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public System.DateTime sendDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public int validity;
        
        public sendVCardRequest()
        {
        }
        
        public sendVCardRequest(string recipient, string firstname, string lastname, string mobilephone, string email, string organization, System.DateTime sendDatetime, string sender, int validity)
        {
            this.recipient = recipient;
            this.firstname = firstname;
            this.lastname = lastname;
            this.mobilephone = mobilephone;
            this.email = email;
            this.organization = organization;
            this.sendDatetime = sendDatetime;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendVCardResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendVCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public sendVCardResponse()
        {
        }
        
        public sendVCardResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSmsFlash", WrapperNamespace="http://ws.bizpack.ro/service.php", IsWrapped=true)]
    internal partial class sendSmsFlashRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public System.DateTime date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public int validity;
        
        public sendSmsFlashRequest()
        {
        }
        
        public sendSmsFlashRequest(string phone, string message, System.DateTime date, string sender, int validity)
        {
            this.phone = phone;
            this.message = message;
            this.date = date;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSmsFlashResponse", WrapperNamespace="http://ws.bizpack.ro/service.php", IsWrapped=true)]
    internal partial class sendSmsFlashResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public sendSmsFlashResponse()
        {
        }
        
        public sendSmsFlashResponse(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkStatus", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class checkStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string messageId;
        
        public checkStatusRequest()
        {
        }
        
        public checkStatusRequest(string messageId)
        {
            this.messageId = messageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkStatusResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class checkStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string status;
        
        public checkStatusResponse()
        {
        }
        
        public checkStatusResponse(string status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="openSession", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class openSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string password;
        
        public openSessionRequest()
        {
        }
        
        public openSessionRequest(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="openSessionResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class openSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sessid;
        
        public openSessionResponse()
        {
        }
        
        public openSessionResponse(string sessid)
        {
            this.sessid = sessid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="closeSession", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class closeSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sessid;
        
        public closeSessionRequest()
        {
        }
        
        public closeSessionRequest(string sessid)
        {
            this.sessid = sessid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="closeSessionResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class closeSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool result;
        
        public closeSessionResponse()
        {
        }
        
        public closeSessionResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSession", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSessionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sessid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public System.DateTime date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int validity;
        
        public sendSessionRequest()
        {
        }
        
        public sendSessionRequest(string sessid, string phone, string message, System.DateTime date, string sender, int validity)
        {
            this.sessid = sessid;
            this.phone = phone;
            this.message = message;
            this.date = date;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSessionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public sendSessionResponse()
        {
        }
        
        public sendSessionResponse(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionWapPush", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSessionWapPushRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sessid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public System.DateTime date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public int validity;
        
        public sendSessionWapPushRequest()
        {
        }
        
        public sendSessionWapPushRequest(string sessid, string phone, string url, string message, System.DateTime date, string sender, int validity)
        {
            this.sessid = sessid;
            this.phone = phone;
            this.url = url;
            this.message = message;
            this.date = date;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionWapPushResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSessionWapPushResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string id;
        
        public sendSessionWapPushResponse()
        {
        }
        
        public sendSessionWapPushResponse(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionVCalendar", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSessionVCalendarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sessid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string location;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string description;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public System.DateTime startDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public System.DateTime endDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public System.DateTime alarmDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public System.DateTime sendDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public int validity;
        
        public sendSessionVCalendarRequest()
        {
        }
        
        public sendSessionVCalendarRequest(string sessid, string recipient, string subject, string location, string description, System.DateTime startDatetime, System.DateTime endDatetime, System.DateTime alarmDatetime, System.DateTime sendDatetime, string sender, int validity)
        {
            this.sessid = sessid;
            this.recipient = recipient;
            this.subject = subject;
            this.location = location;
            this.description = description;
            this.startDatetime = startDatetime;
            this.endDatetime = endDatetime;
            this.alarmDatetime = alarmDatetime;
            this.sendDatetime = sendDatetime;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionVCalendarResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSessionVCalendarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public sendSessionVCalendarResponse()
        {
        }
        
        public sendSessionVCalendarResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionVCard", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSessionVCardRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sessid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string firstname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string lastname;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string mobilephone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string organization;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public System.DateTime sendDatetime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public int validity;
        
        public sendSessionVCardRequest()
        {
        }
        
        public sendSessionVCardRequest(string sessid, string recipient, string firstname, string lastname, string mobilephone, string email, string organization, System.DateTime sendDatetime, string sender, int validity)
        {
            this.sessid = sessid;
            this.recipient = recipient;
            this.firstname = firstname;
            this.lastname = lastname;
            this.mobilephone = mobilephone;
            this.email = email;
            this.organization = organization;
            this.sendDatetime = sendDatetime;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionVCardResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class sendSessionVCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public sendSessionVCardResponse()
        {
        }
        
        public sendSessionVCardResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionSmsFlash", WrapperNamespace="https://www.bizpack.ro/service.php", IsWrapped=true)]
    internal partial class sendSessionSmsFlashRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string sessid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public System.DateTime date;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public int validity;
        
        public sendSessionSmsFlashRequest()
        {
        }
        
        public sendSessionSmsFlashRequest(string sessid, string phone, string message, System.DateTime date, string sender, int validity)
        {
            this.sessid = sessid;
            this.phone = phone;
            this.message = message;
            this.date = date;
            this.sender = sender;
            this.validity = validity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendSessionSmsFlashResponse", WrapperNamespace="https://www.bizpack.ro/service.php", IsWrapped=true)]
    internal partial class sendSessionSmsFlashResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public sendSessionSmsFlashResponse()
        {
        }
        
        public sendSessionSmsFlashResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="showIp", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class showIpRequest
    {
        
        public showIpRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="showIpResponse", WrapperNamespace="https://www.bizpack.ro/wsi/service.php", IsWrapped=true)]
    internal partial class showIpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public showIpResponse()
        {
        }
        
        public showIpResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal interface SMSServicePortChannel : BizPackService.SMSServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    internal partial class SMSServicePortClient : System.ServiceModel.ClientBase<BizPackService.SMSServicePort>, BizPackService.SMSServicePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SMSServicePortClient() : 
                base(SMSServicePortClient.GetDefaultBinding(), SMSServicePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SMSServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSServicePortClient(EndpointConfiguration endpointConfiguration) : 
                base(SMSServicePortClient.GetBindingForEndpoint(endpointConfiguration), SMSServicePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSServicePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SMSServicePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSServicePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SMSServicePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SMSServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendResponse BizPackService.SMSServicePort.send(BizPackService.sendRequest request)
        {
            return base.Channel.send(request);
        }
        
        public string send(string phone, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendRequest inValue = new BizPackService.sendRequest();
            inValue.phone = phone;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendResponse retVal = ((BizPackService.SMSServicePort)(this)).send(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendResponse> BizPackService.SMSServicePort.sendAsync(BizPackService.sendRequest request)
        {
            return base.Channel.sendAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendResponse> sendAsync(string phone, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendRequest inValue = new BizPackService.sendRequest();
            inValue.phone = phone;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.SendSmsResponse BizPackService.SMSServicePort.SendSms(BizPackService.SendSmsRequest request)
        {
            return base.Channel.SendSms(request);
        }
        
        public string SendSms(string username, string password, string source, string destination, string body, bool isUnicode, System.DateTime scheduleDate, string callbackUrl)
        {
            BizPackService.SendSmsRequest inValue = new BizPackService.SendSmsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.source = source;
            inValue.destination = destination;
            inValue.body = body;
            inValue.isUnicode = isUnicode;
            inValue.scheduleDate = scheduleDate;
            inValue.callbackUrl = callbackUrl;
            BizPackService.SendSmsResponse retVal = ((BizPackService.SMSServicePort)(this)).SendSms(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.SendSmsResponse> BizPackService.SMSServicePort.SendSmsAsync(BizPackService.SendSmsRequest request)
        {
            return base.Channel.SendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.SendSmsResponse> SendSmsAsync(string username, string password, string source, string destination, string body, bool isUnicode, System.DateTime scheduleDate, string callbackUrl)
        {
            BizPackService.SendSmsRequest inValue = new BizPackService.SendSmsRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.source = source;
            inValue.destination = destination;
            inValue.body = body;
            inValue.isUnicode = isUnicode;
            inValue.scheduleDate = scheduleDate;
            inValue.callbackUrl = callbackUrl;
            return ((BizPackService.SMSServicePort)(this)).SendSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendSmsAuthKeyResponse BizPackService.SMSServicePort.sendSmsAuthKey(BizPackService.sendSmsAuthKeyRequest request)
        {
            return base.Channel.sendSmsAuthKey(request);
        }
        
        public string sendSmsAuthKey(string username, string authKey, string sender, string recipient, string message, System.DateTime scheduleDate, int validity, string callbackUrl)
        {
            BizPackService.sendSmsAuthKeyRequest inValue = new BizPackService.sendSmsAuthKeyRequest();
            inValue.username = username;
            inValue.authKey = authKey;
            inValue.sender = sender;
            inValue.recipient = recipient;
            inValue.message = message;
            inValue.scheduleDate = scheduleDate;
            inValue.validity = validity;
            inValue.callbackUrl = callbackUrl;
            BizPackService.sendSmsAuthKeyResponse retVal = ((BizPackService.SMSServicePort)(this)).sendSmsAuthKey(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendSmsAuthKeyResponse> BizPackService.SMSServicePort.sendSmsAuthKeyAsync(BizPackService.sendSmsAuthKeyRequest request)
        {
            return base.Channel.sendSmsAuthKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendSmsAuthKeyResponse> sendSmsAuthKeyAsync(string username, string authKey, string sender, string recipient, string message, System.DateTime scheduleDate, int validity, string callbackUrl)
        {
            BizPackService.sendSmsAuthKeyRequest inValue = new BizPackService.sendSmsAuthKeyRequest();
            inValue.username = username;
            inValue.authKey = authKey;
            inValue.sender = sender;
            inValue.recipient = recipient;
            inValue.message = message;
            inValue.scheduleDate = scheduleDate;
            inValue.validity = validity;
            inValue.callbackUrl = callbackUrl;
            return ((BizPackService.SMSServicePort)(this)).sendSmsAuthKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendWapPushResponse BizPackService.SMSServicePort.sendWapPush(BizPackService.sendWapPushRequest request)
        {
            return base.Channel.sendWapPush(request);
        }
        
        public string sendWapPush(string phone, string url, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendWapPushRequest inValue = new BizPackService.sendWapPushRequest();
            inValue.phone = phone;
            inValue.url = url;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendWapPushResponse retVal = ((BizPackService.SMSServicePort)(this)).sendWapPush(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendWapPushResponse> BizPackService.SMSServicePort.sendWapPushAsync(BizPackService.sendWapPushRequest request)
        {
            return base.Channel.sendWapPushAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendWapPushResponse> sendWapPushAsync(string phone, string url, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendWapPushRequest inValue = new BizPackService.sendWapPushRequest();
            inValue.phone = phone;
            inValue.url = url;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendWapPushAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendVCalendarResponse BizPackService.SMSServicePort.sendVCalendar(BizPackService.sendVCalendarRequest request)
        {
            return base.Channel.sendVCalendar(request);
        }
        
        public string sendVCalendar(string recipient, string subject, string location, string description, System.DateTime startDatetime, System.DateTime endDatetime, System.DateTime alarmDatetime, System.DateTime sendDatetime, string sender, int validity)
        {
            BizPackService.sendVCalendarRequest inValue = new BizPackService.sendVCalendarRequest();
            inValue.recipient = recipient;
            inValue.subject = subject;
            inValue.location = location;
            inValue.description = description;
            inValue.startDatetime = startDatetime;
            inValue.endDatetime = endDatetime;
            inValue.alarmDatetime = alarmDatetime;
            inValue.sendDatetime = sendDatetime;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendVCalendarResponse retVal = ((BizPackService.SMSServicePort)(this)).sendVCalendar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendVCalendarResponse> BizPackService.SMSServicePort.sendVCalendarAsync(BizPackService.sendVCalendarRequest request)
        {
            return base.Channel.sendVCalendarAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendVCalendarResponse> sendVCalendarAsync(string recipient, string subject, string location, string description, System.DateTime startDatetime, System.DateTime endDatetime, System.DateTime alarmDatetime, System.DateTime sendDatetime, string sender, int validity)
        {
            BizPackService.sendVCalendarRequest inValue = new BizPackService.sendVCalendarRequest();
            inValue.recipient = recipient;
            inValue.subject = subject;
            inValue.location = location;
            inValue.description = description;
            inValue.startDatetime = startDatetime;
            inValue.endDatetime = endDatetime;
            inValue.alarmDatetime = alarmDatetime;
            inValue.sendDatetime = sendDatetime;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendVCalendarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendVCardResponse BizPackService.SMSServicePort.sendVCard(BizPackService.sendVCardRequest request)
        {
            return base.Channel.sendVCard(request);
        }
        
        public string sendVCard(string recipient, string firstname, string lastname, string mobilephone, string email, string organization, System.DateTime sendDatetime, string sender, int validity)
        {
            BizPackService.sendVCardRequest inValue = new BizPackService.sendVCardRequest();
            inValue.recipient = recipient;
            inValue.firstname = firstname;
            inValue.lastname = lastname;
            inValue.mobilephone = mobilephone;
            inValue.email = email;
            inValue.organization = organization;
            inValue.sendDatetime = sendDatetime;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendVCardResponse retVal = ((BizPackService.SMSServicePort)(this)).sendVCard(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendVCardResponse> BizPackService.SMSServicePort.sendVCardAsync(BizPackService.sendVCardRequest request)
        {
            return base.Channel.sendVCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendVCardResponse> sendVCardAsync(string recipient, string firstname, string lastname, string mobilephone, string email, string organization, System.DateTime sendDatetime, string sender, int validity)
        {
            BizPackService.sendVCardRequest inValue = new BizPackService.sendVCardRequest();
            inValue.recipient = recipient;
            inValue.firstname = firstname;
            inValue.lastname = lastname;
            inValue.mobilephone = mobilephone;
            inValue.email = email;
            inValue.organization = organization;
            inValue.sendDatetime = sendDatetime;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendVCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendSmsFlashResponse BizPackService.SMSServicePort.sendSmsFlash(BizPackService.sendSmsFlashRequest request)
        {
            return base.Channel.sendSmsFlash(request);
        }
        
        public string sendSmsFlash(string phone, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendSmsFlashRequest inValue = new BizPackService.sendSmsFlashRequest();
            inValue.phone = phone;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendSmsFlashResponse retVal = ((BizPackService.SMSServicePort)(this)).sendSmsFlash(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendSmsFlashResponse> BizPackService.SMSServicePort.sendSmsFlashAsync(BizPackService.sendSmsFlashRequest request)
        {
            return base.Channel.sendSmsFlashAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendSmsFlashResponse> sendSmsFlashAsync(string phone, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendSmsFlashRequest inValue = new BizPackService.sendSmsFlashRequest();
            inValue.phone = phone;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendSmsFlashAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.checkStatusResponse BizPackService.SMSServicePort.checkStatus(BizPackService.checkStatusRequest request)
        {
            return base.Channel.checkStatus(request);
        }
        
        public string checkStatus(string messageId)
        {
            BizPackService.checkStatusRequest inValue = new BizPackService.checkStatusRequest();
            inValue.messageId = messageId;
            BizPackService.checkStatusResponse retVal = ((BizPackService.SMSServicePort)(this)).checkStatus(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.checkStatusResponse> BizPackService.SMSServicePort.checkStatusAsync(BizPackService.checkStatusRequest request)
        {
            return base.Channel.checkStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.checkStatusResponse> checkStatusAsync(string messageId)
        {
            BizPackService.checkStatusRequest inValue = new BizPackService.checkStatusRequest();
            inValue.messageId = messageId;
            return ((BizPackService.SMSServicePort)(this)).checkStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.openSessionResponse BizPackService.SMSServicePort.openSession(BizPackService.openSessionRequest request)
        {
            return base.Channel.openSession(request);
        }
        
        public string openSession(string username, string password)
        {
            BizPackService.openSessionRequest inValue = new BizPackService.openSessionRequest();
            inValue.username = username;
            inValue.password = password;
            BizPackService.openSessionResponse retVal = ((BizPackService.SMSServicePort)(this)).openSession(inValue);
            return retVal.sessid;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.openSessionResponse> BizPackService.SMSServicePort.openSessionAsync(BizPackService.openSessionRequest request)
        {
            return base.Channel.openSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.openSessionResponse> openSessionAsync(string username, string password)
        {
            BizPackService.openSessionRequest inValue = new BizPackService.openSessionRequest();
            inValue.username = username;
            inValue.password = password;
            return ((BizPackService.SMSServicePort)(this)).openSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.closeSessionResponse BizPackService.SMSServicePort.closeSession(BizPackService.closeSessionRequest request)
        {
            return base.Channel.closeSession(request);
        }
        
        public bool closeSession(string sessid)
        {
            BizPackService.closeSessionRequest inValue = new BizPackService.closeSessionRequest();
            inValue.sessid = sessid;
            BizPackService.closeSessionResponse retVal = ((BizPackService.SMSServicePort)(this)).closeSession(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.closeSessionResponse> BizPackService.SMSServicePort.closeSessionAsync(BizPackService.closeSessionRequest request)
        {
            return base.Channel.closeSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.closeSessionResponse> closeSessionAsync(string sessid)
        {
            BizPackService.closeSessionRequest inValue = new BizPackService.closeSessionRequest();
            inValue.sessid = sessid;
            return ((BizPackService.SMSServicePort)(this)).closeSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendSessionResponse BizPackService.SMSServicePort.sendSession(BizPackService.sendSessionRequest request)
        {
            return base.Channel.sendSession(request);
        }
        
        public string sendSession(string sessid, string phone, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendSessionRequest inValue = new BizPackService.sendSessionRequest();
            inValue.sessid = sessid;
            inValue.phone = phone;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendSessionResponse retVal = ((BizPackService.SMSServicePort)(this)).sendSession(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendSessionResponse> BizPackService.SMSServicePort.sendSessionAsync(BizPackService.sendSessionRequest request)
        {
            return base.Channel.sendSessionAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendSessionResponse> sendSessionAsync(string sessid, string phone, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendSessionRequest inValue = new BizPackService.sendSessionRequest();
            inValue.sessid = sessid;
            inValue.phone = phone;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendSessionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendSessionWapPushResponse BizPackService.SMSServicePort.sendSessionWapPush(BizPackService.sendSessionWapPushRequest request)
        {
            return base.Channel.sendSessionWapPush(request);
        }
        
        public string sendSessionWapPush(string sessid, string phone, string url, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendSessionWapPushRequest inValue = new BizPackService.sendSessionWapPushRequest();
            inValue.sessid = sessid;
            inValue.phone = phone;
            inValue.url = url;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendSessionWapPushResponse retVal = ((BizPackService.SMSServicePort)(this)).sendSessionWapPush(inValue);
            return retVal.id;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendSessionWapPushResponse> BizPackService.SMSServicePort.sendSessionWapPushAsync(BizPackService.sendSessionWapPushRequest request)
        {
            return base.Channel.sendSessionWapPushAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendSessionWapPushResponse> sendSessionWapPushAsync(string sessid, string phone, string url, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendSessionWapPushRequest inValue = new BizPackService.sendSessionWapPushRequest();
            inValue.sessid = sessid;
            inValue.phone = phone;
            inValue.url = url;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendSessionWapPushAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendSessionVCalendarResponse BizPackService.SMSServicePort.sendSessionVCalendar(BizPackService.sendSessionVCalendarRequest request)
        {
            return base.Channel.sendSessionVCalendar(request);
        }
        
        public string sendSessionVCalendar(string sessid, string recipient, string subject, string location, string description, System.DateTime startDatetime, System.DateTime endDatetime, System.DateTime alarmDatetime, System.DateTime sendDatetime, string sender, int validity)
        {
            BizPackService.sendSessionVCalendarRequest inValue = new BizPackService.sendSessionVCalendarRequest();
            inValue.sessid = sessid;
            inValue.recipient = recipient;
            inValue.subject = subject;
            inValue.location = location;
            inValue.description = description;
            inValue.startDatetime = startDatetime;
            inValue.endDatetime = endDatetime;
            inValue.alarmDatetime = alarmDatetime;
            inValue.sendDatetime = sendDatetime;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendSessionVCalendarResponse retVal = ((BizPackService.SMSServicePort)(this)).sendSessionVCalendar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendSessionVCalendarResponse> BizPackService.SMSServicePort.sendSessionVCalendarAsync(BizPackService.sendSessionVCalendarRequest request)
        {
            return base.Channel.sendSessionVCalendarAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendSessionVCalendarResponse> sendSessionVCalendarAsync(string sessid, string recipient, string subject, string location, string description, System.DateTime startDatetime, System.DateTime endDatetime, System.DateTime alarmDatetime, System.DateTime sendDatetime, string sender, int validity)
        {
            BizPackService.sendSessionVCalendarRequest inValue = new BizPackService.sendSessionVCalendarRequest();
            inValue.sessid = sessid;
            inValue.recipient = recipient;
            inValue.subject = subject;
            inValue.location = location;
            inValue.description = description;
            inValue.startDatetime = startDatetime;
            inValue.endDatetime = endDatetime;
            inValue.alarmDatetime = alarmDatetime;
            inValue.sendDatetime = sendDatetime;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendSessionVCalendarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendSessionVCardResponse BizPackService.SMSServicePort.sendSessionVCard(BizPackService.sendSessionVCardRequest request)
        {
            return base.Channel.sendSessionVCard(request);
        }
        
        public string sendSessionVCard(string sessid, string recipient, string firstname, string lastname, string mobilephone, string email, string organization, System.DateTime sendDatetime, string sender, int validity)
        {
            BizPackService.sendSessionVCardRequest inValue = new BizPackService.sendSessionVCardRequest();
            inValue.sessid = sessid;
            inValue.recipient = recipient;
            inValue.firstname = firstname;
            inValue.lastname = lastname;
            inValue.mobilephone = mobilephone;
            inValue.email = email;
            inValue.organization = organization;
            inValue.sendDatetime = sendDatetime;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendSessionVCardResponse retVal = ((BizPackService.SMSServicePort)(this)).sendSessionVCard(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendSessionVCardResponse> BizPackService.SMSServicePort.sendSessionVCardAsync(BizPackService.sendSessionVCardRequest request)
        {
            return base.Channel.sendSessionVCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendSessionVCardResponse> sendSessionVCardAsync(string sessid, string recipient, string firstname, string lastname, string mobilephone, string email, string organization, System.DateTime sendDatetime, string sender, int validity)
        {
            BizPackService.sendSessionVCardRequest inValue = new BizPackService.sendSessionVCardRequest();
            inValue.sessid = sessid;
            inValue.recipient = recipient;
            inValue.firstname = firstname;
            inValue.lastname = lastname;
            inValue.mobilephone = mobilephone;
            inValue.email = email;
            inValue.organization = organization;
            inValue.sendDatetime = sendDatetime;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendSessionVCardAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.sendSessionSmsFlashResponse BizPackService.SMSServicePort.sendSessionSmsFlash(BizPackService.sendSessionSmsFlashRequest request)
        {
            return base.Channel.sendSessionSmsFlash(request);
        }
        
        public string sendSessionSmsFlash(string sessid, string phone, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendSessionSmsFlashRequest inValue = new BizPackService.sendSessionSmsFlashRequest();
            inValue.sessid = sessid;
            inValue.phone = phone;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            BizPackService.sendSessionSmsFlashResponse retVal = ((BizPackService.SMSServicePort)(this)).sendSessionSmsFlash(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.sendSessionSmsFlashResponse> BizPackService.SMSServicePort.sendSessionSmsFlashAsync(BizPackService.sendSessionSmsFlashRequest request)
        {
            return base.Channel.sendSessionSmsFlashAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.sendSessionSmsFlashResponse> sendSessionSmsFlashAsync(string sessid, string phone, string message, System.DateTime date, string sender, int validity)
        {
            BizPackService.sendSessionSmsFlashRequest inValue = new BizPackService.sendSessionSmsFlashRequest();
            inValue.sessid = sessid;
            inValue.phone = phone;
            inValue.message = message;
            inValue.date = date;
            inValue.sender = sender;
            inValue.validity = validity;
            return ((BizPackService.SMSServicePort)(this)).sendSessionSmsFlashAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BizPackService.showIpResponse BizPackService.SMSServicePort.showIp(BizPackService.showIpRequest request)
        {
            return base.Channel.showIp(request);
        }
        
        public string showIp()
        {
            BizPackService.showIpRequest inValue = new BizPackService.showIpRequest();
            BizPackService.showIpResponse retVal = ((BizPackService.SMSServicePort)(this)).showIp(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BizPackService.showIpResponse> BizPackService.SMSServicePort.showIpAsync(BizPackService.showIpRequest request)
        {
            return base.Channel.showIpAsync(request);
        }
        
        public System.Threading.Tasks.Task<BizPackService.showIpResponse> showIpAsync()
        {
            BizPackService.showIpRequest inValue = new BizPackService.showIpRequest();
            return ((BizPackService.SMSServicePort)(this)).showIpAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SMSServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://www.bizpack.ro/wsi/service.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SMSServicePortClient.GetBindingForEndpoint(EndpointConfiguration.SMSServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SMSServicePortClient.GetEndpointAddress(EndpointConfiguration.SMSServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            SMSServicePort,
        }
    }
}
